### ISSUE TITLE
Add usage/installation Documentation

### ISSUE THREAD

**Issue by luisvt** [mezoni/peg#2]
It would be helpful to add in the documentation a part that tell us the steps needed to use this library.

For example, I don't know if this is a library that runs as a transformer (I doubt it), or if we need to do `pub global activate peg` and then run peg using `peg [options] somefile.peg`

**Comment by mezoni** [comment]
This is not a library. This is a tool (command line generator).
It generates the parsers which source code not depends on anything.

Documentation itself is:

1. Peg grammar (this tool generates itself from this grammar) [peg.peg](https://github.com/mezoni/peg/blob/master/bin/peg.peg)
2. Sample grammars

This tool consists from two utilties:
1. Parser generator [peg.dart](https://github.com/mezoni/peg/blob/master/bin/peg.dart)
2. Grammar formatter [pegfmt.dart](https://github.com/mezoni/peg/blob/master/bin/pegfmt.dart)

Command line help on commands are present in those utilities.

Reading the Wikipedia article also can be useful before use [Parsing expression grammar](https://en.wikipedia.org/wiki/Parsing_expression_grammar).

The generated parsers are fully conforms to Wikipedia article.

Original Bryan Ford's paper highly recommended for reading [Parsing Expression Grammars:
A Recognition-Based Syntactic Foundation](http://www.bford.info/pub/lang/peg.pdf)

Input grammar syntax based on this Bryan Ford's paper.

P.S.

That is.
- The input is PEG grammar with semantic actions
- The output is a source code of PEG parser without dependencies

Recommended usage is standalone manually (by hand) executed tool which generates parsers which can be used later for recognition (parsing).
