### ISSUE TITLE
peg 0.0.53 is not working

### ISSUE THREAD

**Issue by luisvt** [mezoni/peg#5]
steps to reproduce:

1. go to example directory
2. run `peg general arithmetic.peg`
3. arithmetic_parser.dart is created
4. run arithmetic.dart (the wraper program)

Instead showing the result `71` it shows an stackoverflow

**Comment by mezoni** [comment]
Fixed.

## 0.0.54

- Fixed bug in `CharacterClassExpressionGenerator`
- Fixed bug in `LiteralExpressionGenerator`
