### ISSUE TITLE
Use same sintax of peg.js or antlr

### ISSUE THREAD

**Issue by luisvt** [mezoni/peg#7]
It would be great for usability purposes to use the same syntax of antlr or peg.js, in that way we could reuse grammar already created.

I think that antlr syntax would be a little bit better since is already supported by some IDEs and syntax highliters

**Comment by mezoni** [comment]
This software based on the original formulation of Bryan Ford [peg.pdf](http://www.bford.info/pub/lang/peg.pdf]) with the same orginal syntax.
From wikipedia article [Parsing expression grammar](https://en.wikipedia.org/wiki/Parsing_expression_grammar):
The formalism was introduced by Bryan Ford in 2004.

I don't plan to change anything.

**Comment by mezoni** [comment]
Against the background of the fact that Google is losing interest in their own software product (Dart web platform) and reduces the funds for development, I am more than sure that this will not help to increase the popularity of the Dart.
I do not see any reason that would have to spend my free time on something that is not in demand.
